# Generated by Django 6.1 on 2026-08-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название университета')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50, verbose_name='Семестр')),
                ('duration_weeks', models.PositiveIntegerField(verbose_name='Длительность в неделях')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_universities', to='polls.course')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_courses', to='polls.university')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('university', 'course', 'semester'), name='unique_university_course_semester')],
            },
        ),
    ]
